### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by Wierzciu** [overflowy/chat-key#4]
Hello,
did You plan update script? currently dont work with chatgpt/openai api. Use macOS on private computer and have www.elephas.app but on working machine use windows, looking for  alternative but only see script for autohotkey and all dont work with currently chatgpt/openai api.
Will be greatful for information 😃

**Comment by overflowy** [comment]
I just tested the app and everything works correctly. I don't know what issues you are experiencing, maybe your API key is not working correctly?
